export default {
  index: 'Intro',
  ch1_codes_and_error_correcting_codes: 'Codes and Error-Correcting Codes',
  ch2_linear_codes: 'Linear Codes',
  ch3_reed_solomon_codes: 'Reed-Solomon Coeds',
  ch4_rs_proximity: 'Reed-Solomon Proximity',
  ch5_fri_main_challenge: 'FRI Main Challenge',
  ch6_evaluation_domain_for_fri: 'Evaluation Domains for FRI',
  ch7_fri_folding: 'The Algebra Behind FRI Folding',
  ch8_fri_protocol: 'The FRI Protocol (Interactive Version)',
  ch9_commitment: 'Commitment Schemes in FRI',
  ch10_merkle_tree: 'Merkle Trees in FRI',
  ch11_fiat_shamir: 'Non-Interactive FRI via Fiat–Shamir',
  ch12_complexity: 'Complexity Analysis of FRI',
  ch13_soundness: 'Soundness Intuition of FRI',
}